trainingInput:
  pythonVersion: "3.5"
  hyperparameters:
    goal: MAXIMIZE
    hyperparameterMetricTag: val_acc
    maxTrials: 32
    maxParallelTrials: 8
    params:
    - parameterName: learning-rate
      type: DOUBLE
      minValue: 0.00025
      maxValue: 0.002
      scaleType: UNIT_LOG_SCALE
    - parameterName: last-layer-features
      type: DISCRETE
      discreteValues:
      - 512
      - 768
      - 1024
      - 1276
    - parameterName: batch-size
      type: DISCRETE
      discreteValues:
      - 16
      - 24
      - 32
      - 48
    - parameterName: dropout
      type: DOUBLE
      minValue: 0.01
      maxValue: 0.75
      scaleType: UNIT_REVERSE_LOG_SCALE
    - parameterName: lr-sched-step
      type: INTEGER
      minValue: 10
      maxValue: 60
      scaleType: UNIT_LINEAR_SCALE
